### ISSUE TITLE
C++ with compilearg -std=c++11 give a 'virtual memory exhausted: Cannot allocate memory' error

### ISSUE THREAD

**Issue by menghuanpy** [trampgeek/jobe#42] opened 2020-11-28 09:15 UTC
I have a C++ program question, with a " compilearg -std=c++11" option. But Jobe gives me a  'virtual memory exhausted: Cannot allocate memory' error. If no compilearg given, no this error.

I am wondering where the problem is.

**Comment by trampgeek** [comment] 2020-11-28 21:23
The RunGuard sandbox within Jobe limits how much memory a task can use. For C++ the default is 200 MB. The most likely explanation for your problem is that using the different standard has pushed the memory requirements for the task over that limit. Try increasing the memory allowed by setting the memorylimit parameter to a larger value, such as 400 (the units are MB).

**Comment by menghuanpy** [comment] 2020-12-01 03:00
thank you. I will try it later.

**Comment by trampgeek** [comment] 2020-12-04 23:03
Closing for now. Please reopen if the problem is not solved.

**Closed by trampgeek** 2020-12-04 23:03 UTC
